#+include: ./preamble_index.org

#+OPTIONS: num:nil
#+HTML: <!-- <div class="post-meta - 2 min read
#+HTML: -->

* Featured
  # only one entry, with date. single bit of featured content.

  <2021-06-17 Thu>:
  - [[https://github.com/nebhrajani-a/sicp][SICP 1986 Video Notes]]: I've been studying SICP recently (hence the
    brief haitus from writing) from the 1986 Hewlett-Packard
    Television videos. The notes are now available as [[https://nebhrajani-a.github.io/sicp/video_notes/][HTML]] (WIP), and
    [[https://raw.githubusercontent.com/nebhrajani-a/sicp/master/video_notes/video_notes.pdf][PDF]] (recommended). Have fun going through them, and consider
    learning Lisp.

* About
  - =lastname: Nebhrajani=
  - =firstname: Aditya=

  I’m a high school senior living in Pune, MH, India. My interests
  include computer programming, electronics, motorcycles, mathematics,
  badminton, guitar, and pedagogy.

  Specific interests: C, Lisp, GNU Emacs, compiler design, algorithm
  analysis, cybersecurity and encryption, C++, \(\mathrm{\LaTeX}\),
  Python, Linux.


* Contact
  - =lastname @ protonmail.com=
  - [[./gpg.txt][GPG]]
  - [[https://github.com/nebhrajani-a][GitHub]]
  - [[https://www.linkedin.com/in/nebhrajani][LinkedIn]]

  Note that /neither/ Protonmail nor PGP/GPG are a good way to
  communicate if you must have 100% security, since email metadata is
  not secure. Use any application that implements the Signal protocol
  instead. Note that there have been claims that Signal is itself a
  honeypot.

* Site
  Most of this site can be navigated using the navigation bar at the
  top of every page.

  This site’s source is on a [[https://github.com/nebhrajani-a/nebhrajani-a.github.io][GitHub repository]]. This site does not use
  trackers, so I can't see that you've visited it. Note, however, that
  the site is hosted by Microsoft's GitHub, so they almost certainly
  can. There is a mid- to long-term plan to migrate to a self-hosted
  website.

  No JavaScript is used other than [[https://www.mathjax.org][MathJax]], a program used to
  convert \(\mathrm{\LaTeX}\) code to MathML for HTML rendering.
  MathJax passes most JavaScript security extensions, including Tor's.

  Most of the site is plain HTML, generated by Emacs' Org mode. CSS is
  used for most of the styling. This site is designed to be entirely
  readable and navigable using a text-based browser without any loss
  in functionality.

  As of now, no part of this site has a comment section, since I don't
  have the time to moderate for civility.
