#+include: ../posts/preamble_posts.org

#+OPTIONS: num:nil
#+HTML: <!-- <div class="post-meta - 1 min read
#+HTML: -->

Some of the stuff I've written:

1. [[./nss2021.pdf][Erebor [2.4M]​]]: A submission to the [[https://space.nss.org/settlement/nasa/Contest/][NSS Space Settlement Contest
   2021]], in collaboration with Arnav Kalgutkar. Won the third prize in
   the 12th Grade Small Group category.

   *Abstract:* This paper
   presents a novel design for a mobile self-sustaining asteroid
   mining colony (population: 7500) that significantly improves upon
   previous designs' structure, energy requirement, total mass, and construction complexity. Mined ores are
   processed in-situ, adding value and facilitating distribution. Exports
   are carried out using secondary spacecraft. The structure itself is
   designed to minimize mass and mechanical complexity. Of note is the
   creation of a `shell' structure around rotating torii, which is used
   for aeroponics, radiation shielding, rotation using magnets, and
   internal transport between rotating and non-rotating components via
   mag-lev trains. A pebble-bed nuclear reactor is the primary power
   source, and its heat used for nuclear thermal propulsion. Future
   prospects include diversifying export destinations and creating more
   colonies, aiding space colonization.

2. [[./nss2021_errata.pdf][Errata to Erebor [93K]​]]: A record of errors in /Erebor/.
